version: "3"

services:
  todoapi:
    build: .
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=mongodb://db:27017
      - DATABASE_NAME=todoapi
  db:
    image: mongo:latest
    volumes:
      - ./mongodb:/data/db
    ports:
      - 27017:27017
